name: Android Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'app/**'
      - 'build.gradle*'
      - 'settings.gradle*'
      - 'gradle/**'
      - '.github/workflows/android.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'app/**'
      - 'build.gradle*'
      - 'settings.gradle*'
      - 'gradle/**'
      - '.github/workflows/android.yml'
  workflow_dispatch:

jobs:
  build:
    uses: SynclineCode/CodeFlow-Build/.github/workflows/android-build.yml@v1
    secrets: inherit
